### ISSUE TITLE
Windows Security/Defender and Google Chrome think HiyaCFW-Helper is actual malware (Trojan Horse) 

### ISSUE THREAD

**Issue by CaptainCrumb999RobloxYT** [mondul/HiyaCFW-Helper#110]
Hello, So.. Today, I was homebrewing my Nintendo DSi with [dsi.cfw.guide](dsi.cfw.guide), and when I downloaded the latest version of HiyaCFW Helper, Google Chrome, (The browser I'm using to download the files) Said that HiyaCFW Helper was "dangerous" so I just kept it.

That was when Windows Security/Defender said that there was a trojan horse* called "Trojan:Win32/Casdet!rfn" in the files of HiyaCFW Helper. I'm pretty sure that it was for Windows 10, So I just blocked it.

 I'm guessing this thing was a trick to **BRICK** your DSi or PC. It says that "If you can’t download it because it’s a “virus”, check for an allow button or use a different browser, it’s not actually a virus" But I'm sure they were just bricking users' DSi and eventually it would spread to other DSis via Wi-Fi.

 Anyway, Please fix this bug because I think that your CFW is Dangerous and Please, Please, Please fix the bug, @mondul !!!!!!

- @CaptainCrumb999RobloxYT

*#108, #106, #99, #97, #95, #87, #83, #82, #38, #37,  #32, #30, #25, #20, #16, #6, #4.

**Comment by Kodtiz3D** [comment]
The "Trojan" that Windows Defender thinks the Helper is largely due to the fact that it's a Python executable. Rather than just a Python script. It's an issue with Defender, not the software. Use the Python version for the time being, ensuring you have Python 3 installed.
Malware for DS/i just doesn't exist as things are ran in bare metal. The most it would be is a bricker, but it would be a dedicated piece of homebrew and it would be known very quickly. Windows Defender only cares about Win10 capable exploitation, not for other products.

This program is safe if you look through the script.

**Comment by Kodtiz3D** [comment]
Also issue 6, 16 (macOS), 20, 30, 32, 37 (macOS), 38 (macOS), 82, 83 (macOS), 87, and 95(?) aren't related to malware or Windows Defender. Please don't necrobump old closed issues.

**Comment by Epicpkmn11** [comment]
As Kodtiz3D said, it's simply because this is a Python script made into an exe for convenience, which antiviruses love to pretend are viruses and we can't really do much about it sadly.

You can look through the code yourself ([`HiyaCFW_Helper.py`](https://github.com/mondul/HiyaCFW-Helper/blob/master/HiyaCFW_Helper.py)) if you're still concerned we're trying to trick you into harming your DSi or PC ;P

**Comment by CaptainCrumb999RobloxYT** [comment]
Ok, So:
The Trojan that Windows Defender is because its a Python EXE. It's an issue with Windows Defender, Not the software. I know I should use the Python Version (because I have Python 3.8 Installed) now that I think about it.

I like to think that Malware for the DS/i are brickers (that are a piece of homebrew which would be known very quickly*
Wow. I didn't know that it was only for Win10.
Wait, It's Actually Safe? Wow. 

*https://youtu.be/IkujJZtWW7U?t=10 (0:10-1:10)
